api_flow:
  build: .
  environment:
    MYENV: EXAMPLE
  volumes:
    - .:/code
web_migrate:
  extends:
    service: api_flow
  command: python manage.py migrate
web_run:
  extends:
    service: api_flow
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"